<div class="row">

    <div class="col-sm-12 mt-4">
        <h4> Dados da sessão </h1>
        <hr />
    </div>

    <div class="col-sm-6">
        <label for="host"> Servidor:porta </label>
        <input type="text" name="host" id="host" class="form-control" />
    </div>
    
    <div class="col-sm-3">
        <label for="name"> Aparelho </label>
        <input type="text" name="name" id="name" class="form-control" />
    </div>

    <div class="col-sm-3">
        <label for="session"> Nome da sessão (session)</label>
        <input type="text" name="session" id="session" class="form-control" />
    </div>

    <div class="col-sm-6">
        <label for="sessionkey"> Chave da sessão (sessionkey) </label>
        <input type="text" name="sessionkey" id="sessionkey" class="form-control" />
    </div>

    <div class="col-sm-6">
        <label for="apitoken"> API Token (apitoken) </label>
        <input type="text" name="apitoken" id="apitoken" class="form-control" />
    </div>

    <div class="col-sm-12">
        <label for="description"> Descrição </label>
        <textarea name="description" id="description" class="form-control"> </textarea>
    </div>

</div>

<div class="row">

    <div class="col-sm-12 mt-4">
        <h4> Webhook </h1>
        <hr />
    </div>

    <div class="col-sm-6">
        <label for="wa_status"> Webhook status </label>
        <input type="text" name="wa_status" id="wa_status" class="form-control" />
    </div>

    <div class="col-sm-6">
        <label for="wa_status"> Webhook status </label>
        <input type="text" name="wa_status" id="wa_status" class="form-control" />
    </div>


    <div class="col-sm-6">
        <label for="wa_status"> Webhook status </label>
        <input type="text" name="wa_status" id="wa_status" class="form-control" />
    </div>


    <div class="col-sm-6">
        <label for="wa_status"> Webhook status </label>
        <input type="text" name="wa_status" id="wa_status" class="form-control" />
    </div>

</div>