<?php
    $var = "teste";

    //var_dump($sessoes);exit();
?>

<div class="row mt-4">
    <div class="col-md-12"> <a href="<?= $this->url('sessoes') ?>/adicionar" class="btn btn-info float-end"> Adicionar sessão </a> </div>
</div>

<div class="row mt-4">

    <?php if(isset($sessoes) and count($sessoes) > 0)
    { ?>
        <?php foreach ($sessoes as $sessao) : ?>
            <div class="col-md-3">
                <div class="card mt-2">

                    <div class="card-header">
                        <h2 class="card-title text-center session-status_<?=preg_replace('/\s+/', '', $sessao->getSession())?>">
                            <?php 
                            if($sessao->getStatus() == '1') {
                                echo '<i class="fas fa-check-circle text-success"></i> Online!';
                            } else {
                                echo '<i class="fas fa-times-circle text-danger"></i> Offline!';
                            }?>
                        </h2>
                    </div>

                    <div class="card-body text-center">
                        <?php 
                            if($sessao->getStatus() == '1') {
                                echo '<img id="situacao_'.preg_replace('/\s+/', '', $sessao->getSession()).'" src="https://uxwing.com/wp-content/themes/uxwing/download/34-crime-security-military-law/security.svg" style="width:100px" alt="" />';
                            } else {
                                echo '<img id="situacao_'.preg_replace('/\s+/', '', $sessao->getSession()).'" src="https://uxwing.com/wp-content/themes/uxwing/download/13-time-date/no-time.svg" style="width:120px" alt="" />';
                        }?>
                        <br />
                        <span id="messages_<?=preg_replace('/\s+/', '', $sessao->getSession())?>" style="font-size:12px;"></span>
                        <hr/>
                        <span style="float:left;text-align:left;font-size:14px;">
                            <input type="hidden" id="server_<?=$sessao->getId()?>" value="<?=$sessao->getServer()?>" />
                            <strong> <i class="fas fa-mobile"></i> </strong> &nbsp; <?=$sessao->getSession()?> <br />
                            <strong> <i class="fas fa-link"></i> </strong> <?=$sessao->getName()?> <br />
                            <strong> <i class="fas fa-key"></i></strong> </strong> <?=$sessao->getSessionkey()?> <br />
                            <hr style="margin-top:5px;margin-bottom:2px;"/>
                            <span style="font-size:12px;"> <?=$sessao->getServer()?> </a>
                            <span style="font-size:10px;"> <?=$sessao->getApiToken()?> </a>
                        </span>

                    </div>

                    <div class="card-footer text-center">
                        <a class="btn btn-info" href="<?=$this->url('sessoes', ['action' => 'editar', 'id' => $sessao->getId()]) ?>"> Editar </a>
                        
                        <?php 
                            if($sessao->getStatus() == '1') {
                                echo '<button class="btn btn-danger btn-close_'.preg_replace('/\s+/', '', $sessao->getSession()).'" onclick="close()" target="_blank">Desconectar &raquo;</button>';
                            } else {
                                echo '<button class="btn btn-success btn-start_'.preg_replace('/\s+/', '', $sessao->getSession()).'" onclick="start('.$sessao->getId().')" target="_blank">Conectar &raquo;</button>';
                        }?>
                        

                    </div>

                </div>
            </div>
        <?php endforeach; ?>
    <?php } else { ?>
        <div class="col-sm-12"> <h3> Nenhuma sessão encontrada </h3> </div>
    <?php } ?>

</div>

<!-- Modal -->
<div class="modal fade" id="modalSession" tabindex="-1" role="dialog" aria-labelledby="modalSessionLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalSessionLabel">Retorno da API</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>