<?php
    $var = "teste";

    //var_dump($sessoes);exit();
?>

<div class="row mt-4">
    <div class="col-md-12"> <a href="<?= $this->url('sessoes') ?>/adicionar" class="btn btn-info float-end"> Adicionar sessão </a> </div>
</div>

<div class="row mt-4">

    <?php if(isset($sessoes) and count($sessoes) > 0)
    { ?>
        <?php foreach ($sessoes as $sessao) : ?>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title text-center">
                            <?php 
                            if($sessao->getStatus() == '1') {
                                echo '<i class="fas fa-check-circle text-success"></i> Online!';
                            } else {
                                echo '<i class="fas fa-times-circle text-danger"></i> Offline!';
                            }?>
                        </h2>
                    </div>

                    <div class="card-body text-center">
                        <?php 
                            if($sessao->getStatus() == '1') {
                                echo '<img src="https://uxwing.com/wp-content/themes/uxwing/download/34-crime-security-military-law/security.svg" style="width:100px" alt="" />';
                            } else {
                                echo '<img src="https://uxwing.com/wp-content/themes/uxwing/download/13-time-date/no-time.svg" style="width:120px" alt="" />';
                        }?>
                        <hr />
                        <strong> Nome: </strong> <?=$sessao->getSession()?> <br />
                        <strong> Key:</strong> </strong> <?=$sessao->getSessionkey()?> <br />
                        <hr />
                        <a class="btn btn-danger pull-right" href="#" target="_blank">Desconectar &raquo;</a>
                        <br />
                        <a href="<?=$this->url('sessoes', ['action' => 'editar', 'id' => $sessao->getId()]) ?>"> Editar </a>
                    </div>

                </div>
            </div>
        <?php endforeach; ?>
    <?php } else { ?>
        <div class="col-sm-12"> <h3> Nenhuma sessão encontrada </h3> </div>
    <?php } ?>

</div>