<div class="jumbotron">
    <h1>Bem vindo ao <span class="zf-green">Painel MyZap</span></h1>

    <p>
    Parabéns! Você instalou com sucesso o Painel do MyZap,
    agora é so fazer login, para iniciar e gerenciar suas sessões da API do MyZap 2.0
    </p>
    <p><a class="btn btn-success btn-lg" href="#" target="_blank">Fazer login &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"><i class="fas fa-coins"></i>  Servidor gratuito</h2>
            </div>
            <div class="card-body">
                <p>
                    O site APIGRATIS disponibiliza servidores gratuitos de envio de mensagens do WhatsApp utilizando o MyZap 2.0.
                </p>

                <p><a class="btn btn-success pull-right" href="https://apigratis.com.br/" target="_blank">Acessar agora &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"><i class="fab fa-whatsapp"></i> Conheça o MyZap</h2>
            </div>
            <div class="card-body">
                <p>
                   Conheça mais sobre os criadores da API do MyZap 2.0, e faça download do repositorio totalmente gratuito.
                </p>

                <p><a class="btn btn-info pull-right" href="https://github.com/edupoli/MyZap2.0" target="_blank">GitHub.com &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"><i class="fas fa-question-circle"></i> Ajuda e suporte</h2>
            </div>
            <div class="card-body">
                <p>
                   O serviço de suporte é pago, e vem incluso no plano business. A ajuda da comunidade é feito atravez do <a href="https://chat.whatsapp.com/CCeH52Qzxh5IJzoT0Oeb4T"> Grupo de WhatsApp </a>. 
                </p>

                <p><a class="btn btn-info pull-right" href="https://chat.whatsapp.com/CCeH52Qzxh5IJzoT0Oeb4T" target="_blank">Entrar no grupo &raquo;</a></p>
            </div>
        </div>
    </div>
    
</div>
